# Generated by Django 3.2.3 on 2021-12-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.CharField(max_length=100, null=True)),
                ('Explanation', models.CharField(max_length=255, null=True)),
                ('Date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='Blog')),
                ('lesson', models.FileField(upload_to='pdf')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('Courses_time', models.CharField(max_length=50, null=True)),
                ('Courses_explanation', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(upload_to='Courses')),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ebeveyn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebeveynName', models.CharField(max_length=100, null=True)),
                ('studentName', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100, null=True)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=220)),
                ('telephone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('twitter', models.URLField(max_length=254)),
                ('facebook', models.URLField(max_length=254)),
                ('instagram', models.URLField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Future',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', models.CharField(max_length=100, null=True)),
                ('Explanation', models.CharField(max_length=255, null=True)),
                ('month', models.CharField(choices=[('security', 'güvenlik'), ('reading', 'okuma'), ('diploma', 'diploma'), ('education', 'egitim'), ('jigsaw', 'yapboz'), ('kids', 'cocuk')], default='security', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('AltString', models.CharField(max_length=25, null=True)),
                ('image', models.ImageField(upload_to='Galery')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('brans', models.CharField(max_length=100, null=True)),
                ('Certificate', models.BooleanField(default=True)),
                ('explanation', models.CharField(max_length=255, null=True)),
                ('twitter', models.URLField(max_length=254)),
                ('facebook', models.URLField(max_length=254)),
                ('instagram', models.URLField(max_length=254)),
                ('image', models.ImageField(upload_to='teacher')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
